const actionKeys = {
    MARK_GET_ALL_USER: 'MARK_GET_ALL_USER',
    MARK_GET_USER_LIST_SUCCESS: 'MARK_GET_USER_LIST_SUCCESS',
    MARK_GET_USER_LIST_ERROR: 'MARK_GET_USER_LIST_ERROR',
    MARK_GET_USER_LIST_LOADING: 'MARK_GET_USER_LIST_LOADING',
    // user details
    MARK_GET_USER_DETAILS_SUCCESS: 'MARK_GET_USER_DETAILS_SUCCESS',
    MARK_GET_USER_DETAILS_ERROR: 'MARK_GET_USER_DETAILS_ERROR',
    MARK_GET_USER_DETAILS_LOADING: 'MARK_GET_USER_DETAILS_LOADING',
    // Update user keys
    MARK_UPDATE_USER_SUCCESS: 'MARK_UPDATE_USER_SUCCESS',
    MARK_UPDATE_USER_LOADING: 'MARK_UPDATE_USER_LOADING',
    MARK_UPDATE_USER_ERROR: 'MARK_UPDATE_USER_ERROR',
    //delete user keywords
    MARK_DELETE_USER_SUCCESS: 'MARK_DELETE_USER_SUCCESS',
    MARK_DELETE_USER_LOADING: 'MARK_DELETE_USER_LOADING',
    MARK_DELETE_USER_ERROR: 'MARK_DELETE_USER_ERROR',
    //create user keywords
    MARK_CREATE_SUCCESS: 'MARK_CREATE_SUCCESS',
    MARK_CREATE_LOADING: 'MARK_CREATE_LOADING',
    MARK_CREATE_ERROR: 'MARK_CREATE_ERROR'
}

export default actionKeys;